#!/bin/bash

# Verifica a branch onde o commit está sendo efetuado
target_branch=$(git rev-parse --abbrev-ref HEAD)
echo "$target_branch"
# Lista de branches bloqueadas
blocked_branches=("main" "staging")

# Check if the pushed branch is blocked
if [[ "${blocked_branches[@]}" == "$target_branch" ]]; then
	echo "Merge na branch $branch_name não é permitido"
	exit 1
fi