#!/bin/bash

# Verifica a branch onde o commit está sendo efetuado
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Lista de branches bloqueadas
blocked_branches=("main" "staging")

# Check if the pushed branch is blocked
if [[ "${blocked_branches[@]}" =~ "$branch_name" ]]; then
	echo "Commit na branch $branch_name não é permitido"
	exit 1
fi